// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/rohanray/modular-microsvc-dapr-todo/db-go-ent-grpc/ent/schema"
	"github.com/rohanray/modular-microsvc-dapr-todo/db-go-ent-grpc/ent/todo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescTask is the schema descriptor for task field.
	todoDescTask := todoFields[0].Descriptor()
	// todo.TaskValidator is a validator for the "task" field. It is called by the builders before save.
	todo.TaskValidator = todoDescTask.Validators[0].(func(string) error)
	// todoDescCreatedAt is the schema descriptor for created_at field.
	todoDescCreatedAt := todoFields[1].Descriptor()
	// todo.DefaultCreatedAt holds the default value on creation for the created_at field.
	todo.DefaultCreatedAt = todoDescCreatedAt.Default.(func() time.Time)
}
